### PR TITLE
Git/week1

### PR DESCRIPTION
**Pull request by STEP0HEN**
git homework week 1

### CODE REVIEW

**Comment by martamatos** [comment]
Good job Stephen! :)
The only thing is that i'm pretty sure you created the branch git/week1 when you were in the branch git_example, and you should have created it when you were in master. Does this make sense to you?

Now, can you add a fourth country to the file countries.txt and push again please? So the pull request will be updated :)

**Comment by martamatos** [comment]
Great! Well done! :)
You can now merge this pull request into master :)

**Comment by STEP0HEN** [comment]
I just did and it says pull request successfully merged and closed.

**Comment by martamatos** [comment]
Yep! Good job! :)

**Comment by STEP0HEN** [comment]
Thank you. :)

Should I do it all over again to get the correct link in slack?

**Comment by martamatos** [comment]
Naaa, no need to.
From now on, just remember to create your homework branches when you are on master :)

**Comment by STEP0HEN** [comment]
Okay, thank you. I'll keep that in mind right next to "git branch". :)

**Pull request merged**
